# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM ubuntu:jammy as base_build

# TF-serving 2.16.0
ARG TF_SERVING_VERSION_GIT_BRANCH=r2.16
ARG TF_SERVING_VERSION_GIT_COMMIT=0d726954f36a2b6c6bfb60a4caec311f2b3e3101

LABEL maintainer=Jason.Furmanek@amd.com
LABEL tensorflow_serving_github_branchtag=${TF_SERVING_VERSION_GIT_BRANCH}
LABEL tensorflow_serving_github_commit=${TF_SERVING_VERSION_GIT_COMMIT}

ARG GPU_DEVICE_TARGETS="gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942 gfx1030 gfx1100"

# Install build dependencies
COPY setup.packages.sh setup.packages.sh
COPY builder.packages.txt builder.packages.txt
RUN /setup.packages.sh /builder.packages.txt

# Install ROCM
ARG ROCM_VERSION=6.2.0
ARG ROCM_URL
ARG ROCM_BUILD_NAME
ARG ROCM_BUILD_NUM
ARG CUSTOM_INSTALL
ENV ROCM_VERSION=${ROCM_VERSION}
ARG ROCM_PATH=/opt/rocm-${ROCM_VERSION}
ENV ROCM_PATH=${ROCM_PATH}
COPY ${CUSTOM_INSTALL} /${CUSTOM_INSTALL}
COPY setup.rocm.sh /setup.rocm.sh
COPY devel.packages.rocm.txt /devel.packages.rocm.txt
COPY setup_pining.sh /setup_pining.sh
COPY custom_install.sh /custom_install.sh
RUN /setup.rocm.sh $ROCM_VERSION jammy $ROCM_URL $ROCM_BUILD_NAME $ROCM_BUILD_NUM

RUN if [ -n "$ROCM_BUILD_NUM" ] && [ -n "$ROCM_BUILD_NAME" ]; then \  
        echo "Both ROCM_BUILD_NUM and ROCM_BUILD_NAME are set."; \
        apt update -y; \  
        chmod +x /custom_install.sh; \  
        /custom_install.sh ${ROCM_VERSION} ${ROCM_BUILD_NAME} ${ROCM_BUILD_NUM}; \  
    else \  
        wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/jammy/amdgpu-install_6.2.60204-1_all.deb; \  
        apt install -y ./amdgpu-install_6.2.60204-1_all.deb; \  
        apt update; \  
        apt install -y amdgpu-dkms rocm; \  
    fi  

# Setup Python environment. PYTHON_VERSION is e.g. "python3.8"
ARG PYTHON_VERSION=3.10
COPY setup.build-python_ubuntu.sh /setup.build-python_ubuntu.sh
COPY devel.requirements.txt /devel.requirements.txt
RUN /setup.build-python_ubuntu.sh $PYTHON_VERSION devel.requirements.txt

# Set up Bazel
ENV BAZEL_VERSION 6.4.0
WORKDIR /
RUN mkdir /bazel && \
    cd /bazel && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE && \
    chmod +x bazel-*.sh && \
    ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    cd / && \
    rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh

# Build TensorFlow with the ROCm configuration
ENV CI_BUILD_PYTHON python

ENV HCC_HOME=$ROCM_PATH/hcc
ENV HIP_PATH=$ROCM_PATH/hip
ENV OPENCL_ROOT=$ROCM_PATH/opencl
ENV PATH="$HCC_HOME/bin:$HIP_PATH/bin:${PATH}"
ENV PATH="$ROCM_PATH/bin:${PATH}"
ENV PATH="$OPENCL_ROOT/bin:${PATH}"


# Set TMP for nvidia build environment
ENV TMP="/tmp"

# Download TF Serving sources (optionally at specific commit).
WORKDIR /tensorflow-serving
RUN curl -sSL --retry 5 https://github.com/tensorflow/serving/tarball/${TF_SERVING_VERSION_GIT_COMMIT} | tar --strip-components=1 -xzf -
COPY serving.patch001 /tensorflow-serving
RUN patch -p1 < serving.patch001



FROM base_build as binary_build

ARG ROCM_BUILD_NAME
ARG ROCM_BUILD_NUM
# Build, and install TensorFlow Serving
ARG TF_SERVING_BUILD_OPTIONS="--config=release"
RUN echo "Building with build options: ${TF_SERVING_BUILD_OPTIONS}"
ARG TF_SERVING_BAZEL_OPTIONS=""
RUN echo "Building with Bazel options: ${TF_SERVING_BAZEL_OPTIONS}"
ARG ROCM_PATH=/opt/rocm-${ROCM_VERSION}

# Download tensorflow-rocm for org_tensorflow override
ENV ROCM_TF_FORK_REPO="https://github.com/ROCmSoftwarePlatform/tensorflow-upstream"
ENV ROCM_TF_FORK_BRANCH="r2.16-rocm-enhanced"
RUN rm -rf /tmp/tensorflow-upstream || true && \
    git clone -b ${ROCM_TF_FORK_BRANCH} ${ROCM_TF_FORK_REPO} /tmp/tensorflow-upstream

    RUN ls -la ${ROCM_PATH}

# Check if the ROCm directory exists  
RUN ROCM_DIR=$(ls -d /opt/rocm-* 2>/dev/null || echo "") && \  
    if [ -n "$ROCM_DIR" ]; then \  
      echo "ROCm directory exists: $ROCM_DIR"; \  
    else \  
      echo "Error: ROCm directory does not exist."; \  
      exit 1; \  
    fi  

ARG ROCM_PATH=/opt/rocm-${ROCM_VERSION} 
ENV ROCM_PATH=${ROCM_PATH}
ENV ROCM_VERSION=${ROCM_VERSION}

RUN ROCM=$(ls -d /opt/rocm-*) && \
    bazel build --color=yes --curses=yes --copt="-fPIC"\
    --override_repository=org_tensorflow=/tmp/tensorflow-upstream \
    --crosstool_top=@local_config_rocm//crosstool:toolchain \
    --define=using_rocm_hipcc=true \
    --define=tensorflow_mkldnn_contraction_kernel=0 \
    --repo_env TF_NEED_ROCM=1 \
    ${TF_SERVING_BAZEL_OPTIONS} \
    --verbose_failures \
    --output_filter=DONT_MATCH_ANYTHING \
    --action_env ROCM_PATH=$ROCM \
    --action_env=TF_PYTHON_VERSION=$PYTHON_VERSION \
    ${TF_SERVING_BUILD_OPTIONS} \
    --copt=-Wno-stringop-truncation \
    tensorflow_serving/model_servers:tensorflow_model_server && \
    cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server \
    /usr/local/bin/

# Build and install TensorFlow Serving API
RUN ROCM=$(ls -d /opt/rocm-*) && \
    bazel build --color=yes --curses=yes \
    --override_repository=org_tensorflow=/tmp/tensorflow-upstream \
    --crosstool_top=@local_config_rocm//crosstool:toolchain \
    --define=using_rocm_hipcc=true \
    --define=tensorflow_mkldnn_contraction_kernel=0 \
    --repo_env TF_NEED_ROCM=1 \
    ${TF_SERVING_BAZEL_OPTIONS} \
    --verbose_failures \
    --output_filter=DONT_MATCH_ANYTHING \
    --action_env ROCM_PATH=$ROCM \
    ${TF_SERVING_BUILD_OPTIONS} \
    tensorflow_serving/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package \
    /tmp/pip && \
    pip --no-cache-dir install --upgrade \
    /tmp/pip/tensorflow_serving_api_gpu-*.whl && \
    rm -rf /tmp/pip

# Remove tensorflow-gpu and add tensorflow-rocm
ARG INST_TF_ROCM_WHL_SCRIPT
COPY ./${INST_TF_ROCM_WHL_SCRIPT} /tmp/${INST_TF_ROCM_WHL_SCRIPT}
RUN if [ -n "${INST_TF_ROCM_WHL_SCRIPT}" ]; then bash /tmp/${INST_TF_ROCM_WHL_SCRIPT} && \
    rm -f /${INST_TF_ROCM_WHL_SCRIPT}; fi



FROM binary_build as clean_build
# Clean up Bazel cache when done.
RUN bazel clean --expunge --color=yes && \
    rm -rf /root/.cache
CMD ["/bin/bash"]

